spring:
  config:
    import: "optional:configserver"
    use-legacy-processing: true

KIS:
  APP_KEY:
  APP_SECRET:
  URL:
    Base: "https://openapi.koreainvestment.com:9443"
    Domestic-Stock-Quotations: "/uapi/domestic-stock/v1/quotations"
  TradingId:
    Stock-Quotation: "FHKST01010100"